swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /words:
    get:
      operationId: words.read_all
      tags:
        - Words
      summary: Read the entire set of words, sorted by distance
      description: Read the entire set of words, sorted by distance
      responses:
        200:
          description: Successfully read words set operation
          schema:
            type: array
            items:
              properties:
                word_id:
                  type: integer
                  description: Id of the word
                word_name:
                  type: string
                  description: The word itself
                distance:
                  type: string
                  description: Distance from target

    post:
      operationId: words.create
      tags:
        - Words
      summary: Create a word
      description: Create a new word
      parameters:
        - name: word
          in: body
          description: Word to create
          required: True
          schema:
            type: object
            properties:
              word_name:
                type: string
                description: Name of word to create
      responses:
        201:
          description: Successfully created word
          schema:
            properties:
              word_id:
                type: integer
                description: Id of the word
              word_name:
                type: string
                description: Name of word itself
              distance:
                type: string
                description: Distance from target

  /words/search:
    post:
      operationId: words.search
      tags:
        - Words
      summary: Search for a word
      description: Search for a new word
      parameters:
        - name: word
          in: body
          description: Word to search for
          required: True
          schema:
            type: object
            properties:
              word_name:
                type: string
                description: Name of word to create
      responses:
        201:
          description: Successfully searched word
          schema:
            properties:
              word_id:
                type: integer
                description: Id of the word
              word_name:
                type: string
                description: Name of word itself
              distance:
                type: string
                description: Distance from target

  /words/{word_id}:
    get:
      operationId: words.read_one
      tags:
        - Words
      summary: Read one word
      description: Read one word
      parameters:
        - name: word_id
          in: path
          description: Id of the word to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read word from words data operation
          schema:
            type: object
            properties:
              word_id:
                type: integer
                description: Id of the word
              word_name:
                type: string
                description:  name of the word
              distance:
                type: string
                description: Distance from target

    put:
      operationId: words.update
      tags:
        - Words
      summary: Update a word
      description: Update a word
      parameters:
        - name: word_id
          in: path
          description: Id the word to update
          type: integer
          required: True
        - name: word
          in: body
          schema:
            type: object
            properties:
              word_name:
                type: string
                description: Name of the word
      responses:
        200:
          description: Successfully updated word
          schema:
            properties:
              word_id:
                type: integer
                description: Id of the word
              word_name:
                type: string
                description: Name of the word
              distance:
                type: string
                description: Distance from target

    delete:
      operationId: words.delete
      tags:
        - Words
      summary: Delete a word from the words list
      description: Delete a word
      parameters:
        - name: word_id
          in: path
          type: integer
          description: Id of the word to delete
          required: true
      responses:
        200:
          description: Successfully deleted a word


